version: 2
updates:
  # RxBeach
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # React docs
  - package-ecosystem: "npm"
    directory: "/react-docs"
    schedule:
      interval: "daily"
