# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-

      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
      - run: echo "@ardoq:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - run: echo "always-auth=true" >> ~/.npmrc

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: |
            mkdir -p ~/reports/eslint
            yarn lint --format junit --output-file ~/reports/eslint/report.xml

      - run: yarn build

      - run:
          name: Test
          command: |
            mkdir -p ~/reports/ava
            yarn test --tap | ./node_modules/.bin/tap-xunit > ~/reports/ava/report.xml

      - run:
          name: Line coverage
          command: yarn c8 report --reporter=text-lcov | npx coveralls

      - store_test_results:
          path: ~/reports
